MODULE NETCDF_PLUGIN 
 implicit none
CONTAINS

!NETCDF SUBROUTINES

SUBROUTINE CREATENETCDF(ncid,filename)

  USE NETCDF
  
  IMPLICIT NONE
  
  INTEGER :: NCID,STATUS
  
  INTEGER, PARAMETER :: NF90_NOERROR=0
  
  CHARACTER*(*) :: FILENAME
  
  STATUS = NF90_CREATE(PATH=filename,CMODE=0,NCID=ncid)
  
END SUBROUTINE CREATENETCDF

SUBROUTINE DEFINEDIMS(ncid,tid,nt)
  
  USE NETCDF
  
  IMPLICIT NONE
  
  INTEGER :: NCID,STATUS,tid,nt
  
  !        INTEGER :: N1ID,N2ID!,XID,ZID,TID,XIDSTAG,ZIDSTAG
  
  INTEGER, PARAMETER :: NF90_NOERROR=0
  
  !        STATUS = NF90_DEF_DIM(NCID,"X",N1,N1ID)
  !        STATUS = NF90_DEF_DIM(NCID,"Y",N2,N2ID)
  !        STATUS = NF90_DEF_DIM(NCID,"X",N3,XID)
  !        STATUS = NF90_DEF_DIM(NCID,"Z",N4,ZID)
  !        STATUS = NF90_DEF_DIM(NCID,"X-STAGGER",N5,XIDSTAG)
  !        STATUS = NF90_DEF_DIM(NCID,"Z-STAGGER",N6,ZIDSTAG)
  STATUS = NF90_DEF_DIM(NCID,"Time",nt,tid)
END SUBROUTINE DEFINEDIMS

SUBROUTINE CLOSENETCDF(ncid)
  
  USE NETCDF
  
  IMPLICIT NONE
  
  INTEGER :: NCID,STATUS
  
  INTEGER, PARAMETER :: NF90_NOERROR=0
  
  STATUS = NF90_CLOSE(NCID)
  
END SUBROUTINE CLOSENETCDF

SUBROUTINE OPENNETCDF(NCID,NAME)
  
  USE NETCDF
  
  IMPLICIT NONE
  
  INTEGER :: NCID,STATUS
  CHARACTER*(*) :: NAME
  INTEGER, PARAMETER :: NF90_NOERROR=0
  
  STATUS = NF90_OPEN(NAME, NF90_WRITE, NCID)
  
END SUBROUTINE OPENNETCDF

SUBROUTINE DEFINEVAR5D(NCID,NAME,N1ID,N2ID,XID,ZID,TID,VARID)
  
  USE NETCDF
  
  IMPLICIT NONE
  
  INTEGER :: NCID,STATUS,VARID
  INTEGER :: N1ID,N2ID,XID,ZID,TID
  CHARACTER*(*) :: NAME
  
  
  STATUS = NF90_DEF_VAR(NCID,NAME,NF90_DOUBLE,(/N1ID,N2ID,XID,ZID,TID/),VARID)
  
END SUBROUTINE DEFINEVAR5D

SUBROUTINE DEFINEVAR4D(NCID,NAME,N1ID,N2ID,XID,TID,VARID)
  
  USE NETCDF
  
  IMPLICIT NONE
  
  INTEGER :: NCID,STATUS,VARID
  INTEGER :: N1ID,N2ID,XID,ZID,TID
  CHARACTER*(*) :: NAME
  
  
  STATUS = NF90_DEF_VAR(NCID,NAME,NF90_DOUBLE,(/N1ID,N2ID,XID,TID/),VARID)
  
END SUBROUTINE DEFINEVAR4D

SUBROUTINE DEFINEVAR3D(NCID,NAME,XID,ZID,TID,VARID)
  
  USE NETCDF
  
  IMPLICIT NONE
  
  INTEGER :: NCID,STATUS,VARID
  INTEGER :: N1ID,N2ID,XID,ZID,TID
  CHARACTER*(*) :: NAME
  
  
  STATUS = NF90_DEF_VAR(NCID,NAME,NF90_DOUBLE,(/XID,ZID,TID/),VARID)
  
END SUBROUTINE DEFINEVAR3D

SUBROUTINE DEFINEVAR2D(NCID,NAME,XID,TID,VARID)
  
  USE NETCDF
  
  IMPLICIT NONE
  
  INTEGER :: NCID,STATUS,VARID
  INTEGER :: N1ID,N2ID,XID,ZID,TID
  CHARACTER*(*) :: NAME
  
  
  STATUS = NF90_DEF_VAR(NCID,NAME,NF90_DOUBLE,(/XID,TID/),VARID)
  
END SUBROUTINE DEFINEVAR2D


SUBROUTINE DEFINEVAR1D(NCID,NAME,XID,VARID)
  
  USE NETCDF
  
  IMPLICIT NONE
  
  INTEGER :: NCID,STATUS,VARID
  INTEGER :: N1ID,N2ID,XID,ZID,TID
  CHARACTER*(*) :: NAME
  
  STATUS = NF90_DEF_VAR(NCID,NAME,NF90_DOUBLE,(/XID/),VARID)
  
END SUBROUTINE DEFINEVAR1D

SUBROUTINE DEFINEATTS(NCID,VAR,NAME,UNITS)
  
  USE NETCDF
  
  IMPLICIT NONE
  
  INTEGER :: NCID,VAR,STATUS
  
  REAL :: MIN,MAX
  
  CHARACTER*(*)  :: NAME,UNITS
  
  !STATUS = NF90_PUT_ATT(NCID,VAR,"valid_range",real((/min,max/)))
  STATUS = NF90_PUT_ATT(NCID,VAR,"title",NAME)
  STATUS = NF90_PUT_ATT(NCID,VAR,"units",UNITS)
  
END SUBROUTINE DEFINEATTS

SUBROUTINE ENDDEF(NCID)
  
  USE NETCDF
  
  INTEGER :: NCID,STATUS
  
  STATUS = NF90_ENDDEF(NCID)
  
END SUBROUTINE ENDDEF


SUBROUTINE WRITEVAR5D(NCID,DAT,N1,N2,N3,N4,TIME2,NAME)
  
  USE NETCDF
  
  INTEGER :: NCID, VAR,N1,N2,N3,N4,TIME2,status
  CHARACTER*(*) :: NAME
  REAL, DIMENSION(N1,N2,N3,N4) :: DAT
  
  
  STATUS = NF90_INQ_VARID(NCID,NAME,VAR)
  !write(*,*) "here",var
  
  STATUS = NF90_PUT_VAR(NCID,VAR,DAT,START = (/1,1,1,1,TIME2/), COUNT = (/N1,N2,N3,N4,1/))
  !write(*,*) nf90_strerror(status)
  
END SUBROUTINE WRITEVAR5D

SUBROUTINE WRITEVAR4D(NCID,DAT,N1,N2,N3,TIME2,NAME)
  
  USE NETCDF
  
  INTEGER :: NCID, VAR,N1,N2,N3,N4,TIME2,status
  CHARACTER*(*) :: NAME
  REAL, DIMENSION(N1,N2,N3) :: DAT
  
  
  STATUS = NF90_INQ_VARID(NCID,NAME,VAR)
  !write(*,*) "here",var
  
  STATUS = NF90_PUT_VAR(NCID,VAR,DAT,START = (/1,1,1,TIME2/), COUNT = (/N1,N2,N3,1/))
  !write(*,*) nf90_strerror(status)
  
END SUBROUTINE WRITEVAR4D

SUBROUTINE WRITEVAR3D(NCID,DAT,N1,N2,TIME2,NAME)
  
  USE NETCDF
  
  INTEGER :: NCID, VAR,N1,N2,N3,N4,TIME2,STATUS
  CHARACTER*(*) :: NAME
  REAL, DIMENSION(N1,N2) :: DAT
  
  STATUS = NF90_INQ_VARID(NCID,NAME,VAR)
  STATUS = NF90_PUT_VAR(NCID,VAR,DAT,START = (/1,1,TIME2/), COUNT = (/N1,N2,1/))
  
END SUBROUTINE WRITEVAR3D

SUBROUTINE WRITEVAR2D(NCID,DAT,N1,N2,NAME)
  
  USE NETCDF
  
  INTEGER :: NCID, VAR,N1,N2,N3,N4,TIME2,STATUS
  CHARACTER*(*) :: NAME
  REAL, DIMENSION(N1,N2) :: DAT
  
  STATUS = NF90_INQ_VARID(NCID,NAME,VAR)
  STATUS = NF90_PUT_VAR(NCID,VAR,DAT,START = (/1,1/), COUNT = (/N1,N2/))
  
END SUBROUTINE WRITEVAR2D


SUBROUTINE WRITEVAR1D(NCID,DAT,N1,NAME)
  
  USE NETCDF
  
  INTEGER :: NCID, VAR,N1,N2,N3,N4,TIME2,STATUS
  CHARACTER*(*) :: NAME
  REAL, DIMENSION(N1) :: DAT
 
  STATUS = NF90_INQ_VARID(NCID,NAME,VAR)
  STATUS = NF90_PUT_VAR(NCID,VAR,DAT,START = (/1/), COUNT = (/N1/))
  
END SUBROUTINE WRITEVAR1D

SUBROUTINE READVAR5D(NCID,DAT,N1,N2,N3,N4,TIME2,NAME)
  
  USE NETCDF
  
  INTEGER :: NCID, VAR,N1,N2,N3,N4,TIME2,status
  CHARACTER*(*) :: NAME
  REAL, DIMENSION(N1,N2,N3,N4) :: DAT
  
  STATUS = NF90_INQ_VARID(NCID,NAME,VAR)
  !write(*,*) "here",var
  
  STATUS = NF90_GET_VAR(NCID,VAR,DAT,START = (/1,1,1,1,TIME2/), COUNT=(/n1,n2,n3,n4,1/))
  
END SUBROUTINE READVAR5D

SUBROUTINE READVAR3D(NCID,DAT,N1,N2,TIME2,NAME)
  
  USE NETCDF
  
  INTEGER :: NCID, VAR,N1,N2,N3,N4,TIME2,STATUS
  CHARACTER*(*) :: NAME
  REAL, DIMENSION(N1,N2) :: DAT
  
  STATUS = NF90_INQ_VARID(NCID,NAME,VAR)
  STATUS = NF90_GET_VAR(NCID,VAR,DAT,START = (/1,1,TIME2/), COUNT = (/N1,N2,1/))
  
END SUBROUTINE READVAR3D

SUBROUTINE READVAR2D(NCID,DAT,N1,TIME2,NAME)
  
  USE NETCDF
  
  INTEGER :: NCID, VAR,N1,N2,N3,N4,TIME2,STATUS
  CHARACTER*(*) :: NAME
  REAL, DIMENSION(N1) :: DAT
  
  STATUS = NF90_INQ_VARID(NCID,NAME,VAR)
  STATUS = NF90_GET_VAR(NCID,VAR,DAT,START = (/1,TIME2/),count = (/n1,1/))
  
END SUBROUTINE READVAR2D

SUBROUTINE READVAR1D(NCID,DAT,N1,NAME)
  
  USE NETCDF
  
  INTEGER :: NCID, VAR,N1,N2,N3,N4,TIME2,STATUS
  CHARACTER*(*) :: NAME
  REAL, DIMENSION(N1) :: DAT
  
  STATUS = NF90_INQ_VARID(NCID,NAME,VAR)
  STATUS = NF90_GET_VAR(NCID,VAR,DAT,START = (/1/),count = (/n1/))
  
END SUBROUTINE READVAR1D



end MODULE NETCDF_PLUGIN
